[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin/=lib/openzeppelin-contracts/']
exclude = ["src/sourcecode/etherscan-verified/56/0x1bc016c00f8d603c41a582d5da745905b9d034e5/contract/abcc"]


fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
mainnet = "https://eth-mainnet.public.blastapi.io"

bsc = "https://bsc-mainnet.infura.io/v3/163a44154f764ae685e8701a980f1238"                 